### ISSUE TITLE
Addition of T1098.004

### ISSUE THREAD

**Issue by attackjunkee** [bfuzzy1/auditd-attack#4]
replacing "-w /etc/ssh/sshd_config -k T1021_Remote_Services" with "-w /etc/ssh/sshd_config -p w -k T1098.004_SSH_Authorized_Keys" may better align with the updated framework.

There will be another stage for covering the actual <user-home>/.ssh/authorized_keys file but the sshd_config file is also covered under this technique.

Thanks for the consideration and Great Work!

**Comment by bfuzzy1** [comment]
I'll make that change now! Thank you! I need to get this current with the new updates.

**Comment by bfuzzy1** [comment]
Update made. Thanks again!
