### ISSUE TITLE
Att&ck conversions with sub-techniques

### ISSUE THREAD

**Issue by attackjunkee** [bfuzzy1/auditd-attack#5]
Some deprecated to new technique conversions and new sub-techniques have been built upon from your ruleset. Updates are located at: https://github.com/attackjunkee/auditd-attack/blob/master/auditd-attack/auditd-attack.rules 

Hope this helps!
Cheers

**Comment by bfuzzy1** [comment]
@attackjunkee awesome work on this! If you don't mind could you submit a pull request and I'll get these changes pulled into the master repo!

**Comment by bfuzzy1** [comment]
Closed @attackjunkee has pushed in the update. Great work!
